// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LC_BattleFlyWord","status":true,"description":"战斗文字弹幕 V1.1.0","parameters":{"Window Top Y":"0","Window Bottom Y":"500","Min Speed":"2","Max Speed":"6","Font Size":"14","Font Color":"#0000FF"}}
];
