// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LC_BattleFlyWord","status":true,"description":"战斗文字弹幕 V1.2.0","parameters":{"Window Top Y":"0","Window Bottom Y":"300","Min Speed":"5","Max Speed":"10","Font Family":"Ink","Font Italic":"true","Font Outline Color":"#FF0000","Font Outline Width":"5","Font Size":"20","Font Color":"#FFFFFF"}}
];
