// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"--------------------1","status":false,"description":"Core Plugins核心插件","parameters":{}},
{"name":"--------------------2","status":false,"description":"Battle Plugins 战斗插件","parameters":{}},
{"name":"--------------------3","status":false,"description":"Item Plugins 物品插件","parameters":{}},
{"name":"--------------------4","status":false,"description":"Skill Plugins 技能插件","parameters":{}},
{"name":"--------------------5","status":false,"description":"Equip Plugins 装备插件","parameters":{}},
{"name":"--------------------6","status":false,"description":"Status Menu Plugins 身份状态菜单插件","parameters":{}},
{"name":"--------------------7","status":false,"description":"Gameplay Plugins 游戏玩法插件","parameters":{}},
{"name":"--------------------8","status":false,"description":"Movement Plugins 移动插件","parameters":{}},
{"name":"--------------------9","status":false,"description":"Quest Plugins 任务插件","parameters":{}},
{"name":"--------------------10","status":false,"description":"Options Menu 选项菜单","parameters":{}},
{"name":"--------------------11","status":false,"description":"Utility Plugins 多功能插件","parameters":{}},
{"name":"--------------------12","status":false,"description":"DragonBones 龙骨插件","parameters":{}},
{"name":"--------------------13","status":false,"description":"Misc Plugins 实用插件","parameters":{}},
{"name":"YEP_ItemCore","status":true,"description":"v1.29 Changes the way Items are handled for your game\nand the Item Scene, too.","parameters":{"---General---":"","Max Items":"0","Max Weapons":"100","Max Armors":"100","Starting ID":"3000","Random Variance":"0","Negative Variance":"false","Name Format":"%1%2%3%4","Name Spacing":"true","Boost Format":"(+%1)","---Item Scene---":"","Updated Scene Item":"true","List Equipped Items":"true","Show Icon":"true","Icon Size":"128","Font Size":"20","Command Alignment":"center","Recovery Format":"%1 Heal","Add State":"+State","Add Buff":"+Buff","Remove State":"-State","Remove Buff":"-Buff","Maximum Icons":"4","Use Command":"Use %1","Carry Format":"%1/%2","--Independent Items--":"","Midgame Note Parsing":"false"}},
{"name":"Test","status":true,"description":"","parameters":{}},
{"name":"YEP_EquipCore","status":true,"description":"v1.17 Allows for the equipment system to be more flexible to\nallow for unique equipment slots per class.","parameters":{"---General---":"","Text Align":"center","Finish Command":"Finish","Remove Text":"Remove","Remove Icon":"16","Empty Text":"<Empty>","Empty Icon":"16","---Rules---":"","Non-Removable Types":"1","Non-Optimized Types":"5"}}
];
